---
name: Main Build
on:
  push:
    branches:
      - main
env:
  # renovate: datasource=java-version depName=java-jdk
  JAVA_VERSION: '20.0.2+9'
  # renovate: datasource=maven depName=org.apache.maven:maven
  MAVEN_VERSION: '3.9.4'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Set up Maven
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}
      - name: Set up Java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Deploy Snapshot to GitHub Packages
        if: ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode --no-transfer-progress -Dmaven.test.skip=true -Dtree=${{ github.sha }} deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
