---
name: Main Build
on:
  push:
    branches:
      - main
env:
  # renovate: datasource=java-version depName=java-jdk
  JAVA_VERSION: '26.0.0+35'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      code-quality: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Build
        run: ./gradlew build testCodeCoverageReport
      - name: Test Report
        if: always()
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage report
        uses: actions/upload-code-coverage@d8e329117199404bba6fc81efe8093dc7c015e34 # v1.4.2
        with:
          file: build/reports/jacoco/testCodeCoverageReport/cobertura-testCodeCoverageReport.xml
          language: Java
          label: code-coverage/jacoco
      - name: Publish Snapshot
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
