---
name: Main Build
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.project.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Zulu 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
  publish:
    needs:
      - test
    if: ${{ endsWith(needs.test.outputs.version, '-SNAPSHOT') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Zulu 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Deploy with Maven
        run: mvn --batch-mode --no-transfer-progress deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
