---
name: PR Build
on: pull_request
env:
  # renovate: datasource=java-version depName=java-jdk
  JAVA_VERSION: '26.0.0+35'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      code-quality: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - name: Build
        run: ./gradlew build testCodeCoverageReport
      - name: Test Report
        if: always()
        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage report
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@1c15be36fc3733ba839b1dd643bd9556e4426dc1 # v1.4.1
        with:
          file: build/reports/jacoco/testCodeCoverageReport/cobertura-testCodeCoverageReport.xml
          language: Java
          label: code-coverage/jacoco
