---
name: PR Build
on: pull_request
env:
  # renovate: datasource=java-version depName=java-jdk
  JAVA_VERSION: '26.0.0+35'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      code-quality: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6
      - name: Build
        run: ./gradlew build testCodeCoverageReport
      - name: Test Report
        if: always()
        uses: mikepenz/action-junit-report@b7b80d7ac5b1da46d6aaff9fb57ad50d8453bcb3 # v6.6.0
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage report
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@2b21a77928be8d5168c2b9581a67f2adbebacc52 # v1.4.4
        with:
          file: build/reports/jacoco/testCodeCoverageReport/cobertura-testCodeCoverageReport.xml
          language: Java
          label: code-coverage/jacoco
