---
name: Release
on:
  release:
    types:
      - published
env:
  # renovate: datasource=java-version depName=java-jdk
  JAVA_VERSION: '26.0.0+35'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      checks: write
      contents: read
      packages: write
    if: startsWith(github.ref_name, 'v')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Build and Publish to Maven Central
        run: ./gradlew build publishAggregationToCentralPortal -Pversion=${GITHUB_REF_NAME##v}
        env:
          ORG_GRADLE_PROJECT_centralPortalUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_centralPortalPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository -Pversion=${GITHUB_REF_NAME##v}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Report
        if: always()
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
